# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Variables de entorno
    env:
      plataform: aws
      region: us-east
      account: 123456

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Runs a single command using the runners shell
      # - name: Mostrar variables de entorno
      #  run: "Plataforma: ${{env.plataform}} "

      # Runs a set of commands using the runners shell
      - name: Mostrar un mensaje de las variables
        run: |
          echo "Valor de la plataforma: ${{env.plataform}}"
          echo "Valor de la plataforma: ${{env.region}}"
          echo "Valor de la plataforma: ${{env.account}}"
